Import('qtEnv')
libEnv = qtEnv.Clone()

libEnv.Append(CPPPATH = ['#/src/lib'])
libEnv.EnableQt5Modules(['QtWidgets'])

Export('libEnv')

libEnv.Library('FPlot', SConscript('FPlot/SConscript'))
libEnv.Library('MThread', SConscript('MThread/SConscript'))
libEnv.Library('ShootGame', SConscript('ShootGame/SConscript'))
libEnv.Library('ImageUpdate', SConscript('ImageUpdate/SConscript'))
#libEnv.Library('OGL', SConscript('OGL/SConscript'))



