Import('env')

cpps = Split("""
    MainWindow.cpp
    Thread.cpp
    ThreadDialog.cpp
""")

class_objs = []

for cpp in cpps:
    class_obj = env.Object(cpp)
    class_objs.append(class_obj)

Return('class_objs')

